name: Exécution automatique du pipeline

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Lister fichiers récursivement (debug)
        run: ls -R

      - name: Installer Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer scripts.py
        run: python scripts.py

      - name: Upload des résultats JSON
        uses: actions/upload-artifact@v4
        with:
          name: resultats-json
          path: results/

